vpc_cidr_block = "10.0.0.0/16"
subnet_cidr_block = "10.0.10.0/24"
avail_zone = "eu-west-1a"
env_prefix = "dev"
ip_addr = "143.244.37.238/32"
instance_type = "t2.micro"
# public_key_location = "<path to public ssh key location (e.g. id_rsa.pub)"
# private_key_location = "<path to private ssh key location (e.g. id_rsa)"
